use super::*;

#[derive(Clone)]
pub(crate) struct RenderLossEvalConfig {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) extra_seeds: Vec<u64>,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) render: RenderLossConfig,
}

#[derive(Clone)]
pub(crate) struct RenderProxyTrainingConfig {
    pub(crate) target: MeshTargetArg,
    pub(crate) rounds: usize,
    pub(crate) supervised_steps_per_round: usize,
    pub(crate) particles: usize,
    pub(crate) rollout_steps: usize,
    pub(crate) gradient_particles: usize,
    pub(crate) gradient_mode: RenderGradientModeArg,
    pub(crate) finite_diff_eps: f32,
    pub(crate) motion_gain: f32,
    pub(crate) perception_position_gain: f32,
    pub(crate) max_update_norm: f32,
    pub(crate) trajectory_supervision: bool,
    pub(crate) trajectory_render_gain: f32,
    pub(crate) trajectory_mesh_gain: f32,
    pub(crate) trajectory_render_samples: usize,
    pub(crate) liveness_gain: f32,
    pub(crate) liveness_front_radius: f32,
    pub(crate) liveness_update_multiplier: f32,
    pub(crate) coverage_gain: f32,
    pub(crate) coverage_samples: usize,
    pub(crate) coverage_mode: CoverageUpdateModeArg,
    pub(crate) coverage_softness: f32,
    pub(crate) coverage_repulsion_gain: f32,
    pub(crate) coverage_gap_gain: f32,
    pub(crate) coverage_repulsion_radius: f32,
    pub(crate) coverage_normal_weight: f32,
    pub(crate) extent_gain: f32,
    pub(crate) full_coverage_adjoint: bool,
    pub(crate) surface_gain: f32,
    pub(crate) surface_escape_gain: f32,
    pub(crate) opacity_gain: f32,
    pub(crate) material_liveness_gain: f32,
    pub(crate) material_tail_gain: f32,
    pub(crate) material_suppression_update_multiplier: f32,
    pub(crate) material_max_opacity_update: f32,
    pub(crate) scale_gain: f32,
    pub(crate) scale_budget_weight: f32,
    pub(crate) max_opacity_update: f32,
    pub(crate) direct_output_gradient_rms_cap: f32,
    pub(crate) direct_line_search: bool,
    pub(crate) direct_line_search_scales: Vec<f32>,
    pub(crate) direct_material_output_only: bool,
    pub(crate) training_backend: RenderTrainingBackendArg,
    pub(crate) direct_selection_seed_training: bool,
    pub(crate) seed: u64,
    pub(crate) selection_seed: Option<u64>,
    pub(crate) selection_seeds: Vec<u64>,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) render: RenderLossConfig,
    pub(crate) sgd: SgdConfig,
}
