use crate::cli::prelude::*;

#[derive(Clone)]
pub(crate) struct Growth3dValidationConfig {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) extra_seeds: Vec<u64>,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) gate: Growth3dValidationGateArg,
    pub(crate) render: RenderLossConfig,
}

#[derive(Serialize)]
pub(crate) struct CliGrowth3dValidationReport {
    pub(crate) target: MeshTargetArg,
    pub(crate) model: String,
    pub(crate) source: Option<String>,
    pub(crate) position_features: bool,
    pub(crate) local_conditionless_lineage: bool,
    pub(crate) target_conditionless_lineage: bool,
    pub(crate) target_seed_conditionless_lineage: bool,
    pub(crate) target_growth_seed_mode: bool,
    pub(crate) seed_coordinate_scaffold: bool,
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) non_opacity_seed_abs_max: f32,
    pub(crate) initial_color_state: Growth3dColorStateReport,
    pub(crate) final_color_state: Growth3dColorStateReport,
    pub(crate) permutation_consistency: Growth3dPermutationReport,
    pub(crate) seed_perturbation: Growth3dSeedPerturbationReport,
    pub(crate) mean_final_displacement: f32,
    pub(crate) final_opacity: Growth3dOpacityStats,
    pub(crate) final_material_opacity: Growth3dOpacityStats,
    pub(crate) final_material_liveness: Growth3dMaterialLivenessReport,
    pub(crate) activation: Growth3dActivationReport,
    pub(crate) initial_surface: Growth3dSurfaceStats,
    pub(crate) final_surface: Growth3dSurfaceStats,
    pub(crate) initial_active_surface: Growth3dSurfaceStats,
    pub(crate) final_active_surface: Growth3dSurfaceStats,
    pub(crate) initial_active_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) final_active_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) initial_material_visible_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) final_material_visible_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) target_coverage_threshold: f32,
    pub(crate) initial_target_coverage: TargetCoverageStats,
    pub(crate) final_target_coverage: TargetCoverageStats,
    pub(crate) initial_active_target_coverage: TargetCoverageStats,
    pub(crate) final_active_target_coverage: TargetCoverageStats,
    pub(crate) initial_material_visible_target_coverage: TargetCoverageStats,
    pub(crate) final_material_visible_target_coverage: TargetCoverageStats,
    pub(crate) initial_strict_surface_materialization: Growth3dStrictSurfaceMaterializationReport,
    pub(crate) final_strict_surface_materialization: Growth3dStrictSurfaceMaterializationReport,
    pub(crate) final_active_surface_coverage_profile: SurfaceCoverageProfileReport,
    pub(crate) final_material_visible_surface_coverage_profile: SurfaceCoverageProfileReport,
    pub(crate) final_active_surface_normal_coverage: SurfaceNormalCoverageReport,
    pub(crate) final_material_visible_surface_normal_coverage: SurfaceNormalCoverageReport,
    pub(crate) torus_angular_coverage: Option<TorusAngularCoverageReport>,
    pub(crate) extent: Growth3dExtentReport,
    pub(crate) motion: Growth3dMotionReport,
    pub(crate) temporal: Growth3dTemporalReport,
    pub(crate) front: Growth3dFrontReport,
    pub(crate) dormant_drift: Growth3dDormantDriftReport,
    pub(crate) max_motion_per_step: f32,
    pub(crate) render_loss: MultiViewRenderLossReport,
    pub(crate) initial_gaussian_volume: GaussianVolumeStats,
    pub(crate) final_gaussian_volume: GaussianVolumeStats,
    pub(crate) strict_checks: Growth3dStrictChecksReport,
    pub(crate) strict_score: Growth3dStrictScoreReport,
    pub(crate) catalog_sanity: Growth3dCatalogSanityReport,
    pub(crate) robustness: Growth3dRobustnessReport,
    pub(crate) gate: Growth3dValidationGateArg,
    pub(crate) gate_passed: bool,
    pub(crate) strict_passed: bool,
}

#[derive(Serialize)]
pub(crate) struct Growth3dStrictChecksReport {
    pub(crate) passed: bool,
    pub(crate) no_position_features: bool,
    pub(crate) local_conditionless_lineage: bool,
    pub(crate) target_conditionless_lineage: bool,
    pub(crate) target_seed_conditionless_lineage: bool,
    pub(crate) target_growth_seed_mode: bool,
    pub(crate) no_seed_coordinate_scaffold: bool,
    pub(crate) neutral_non_opacity_seed_state: bool,
    pub(crate) sparse_active_seed: bool,
    pub(crate) active_count_growth: bool,
    pub(crate) newly_activated_fraction: bool,
    pub(crate) active_front_expanded: bool,
    pub(crate) active_extent_growth: bool,
    pub(crate) nonzero_motion: bool,
    pub(crate) sustained_motion: bool,
    pub(crate) local_front_coherent: bool,
    pub(crate) dormant_drift_bounded: bool,
    pub(crate) temporal_activation_progressive: bool,
    pub(crate) temporal_geometry_progressive: bool,
    pub(crate) mean_displacement_growth: bool,
    pub(crate) bounded_final_opacity: bool,
    pub(crate) material_visible_particles_live: bool,
    pub(crate) color_state_emerged: bool,
    pub(crate) permutation_consistent: bool,
    pub(crate) surface_mean_improved: bool,
    pub(crate) surface_max_bounded: bool,
    pub(crate) surface_tail_bounded: bool,
    pub(crate) material_visible_surface_tail_bounded: bool,
    pub(crate) target_coverage_mean_improved: bool,
    pub(crate) target_coverage_max_bounded: bool,
    pub(crate) target_coverage_fraction: bool,
    pub(crate) material_visible_target_coverage_fraction: bool,
    pub(crate) surface_coverage_profile: bool,
    pub(crate) material_visible_surface_coverage_profile: bool,
    pub(crate) surface_normal_coverage: bool,
    pub(crate) material_visible_surface_normal_coverage: bool,
    pub(crate) torus_angular_coverage: bool,
    pub(crate) gaussian_scale_budget: bool,
    pub(crate) render_loss_passed: bool,
    pub(crate) failure_reasons: Vec<&'static str>,
}

#[derive(Serialize)]
pub(crate) struct Growth3dStrictScoreReport {
    pub(crate) score: f32,
    pub(crate) hard_failure_penalty: f32,
    pub(crate) temporal_activation_schedule_error: f32,
    pub(crate) temporal_activation_schedule_penalty: f32,
    pub(crate) motion_peak_mean_dx: f32,
    pub(crate) motion_peak_penalty: f32,
    pub(crate) motion_active_step_fraction: f32,
    pub(crate) motion_active_step_penalty: f32,
    pub(crate) motion_sustained_step_fraction: f32,
    pub(crate) motion_sustained_step_penalty: f32,
    pub(crate) mean_final_displacement: f32,
    pub(crate) mean_final_displacement_penalty: f32,
    pub(crate) material_visible_inactive_fraction: f32,
    pub(crate) material_visible_inactive_fraction_penalty: f32,
    pub(crate) material_visible_max_inactive_opacity: f32,
    pub(crate) material_visible_max_inactive_opacity_penalty: f32,
    pub(crate) surface_mean_ratio: f32,
    pub(crate) surface_mean_penalty: f32,
    pub(crate) surface_max_distance: f32,
    pub(crate) surface_max_penalty: f32,
    pub(crate) surface_tail_p99_distance: f32,
    pub(crate) surface_tail_p99_penalty: f32,
    pub(crate) surface_tail_over_threshold_fraction: f32,
    pub(crate) surface_tail_fraction_penalty: f32,
    pub(crate) material_visible_surface_tail_p99_distance: f32,
    pub(crate) material_visible_surface_tail_p99_penalty: f32,
    pub(crate) material_visible_surface_tail_over_threshold_fraction: f32,
    pub(crate) material_visible_surface_tail_fraction_penalty: f32,
    pub(crate) target_coverage_mean_ratio: f32,
    pub(crate) target_coverage_mean_penalty: f32,
    pub(crate) target_coverage_max_distance: f32,
    pub(crate) target_coverage_max_penalty: f32,
    pub(crate) target_coverage_fraction: f32,
    pub(crate) target_coverage_fraction_penalty: f32,
    pub(crate) material_visible_target_coverage_fraction: f32,
    pub(crate) material_visible_target_coverage_penalty: f32,
    pub(crate) active_extent_bbox_ratio: f32,
    pub(crate) active_extent_bbox_penalty: f32,
    pub(crate) active_extent_min_axis_ratio: f32,
    pub(crate) active_extent_min_axis_penalty: f32,
    pub(crate) surface_covered_bin_fraction: f32,
    pub(crate) surface_bin_penalty: f32,
    pub(crate) surface_mean_bin_covered_fraction: f32,
    pub(crate) surface_coverage_mean_penalty: f32,
    pub(crate) material_visible_surface_covered_bin_fraction: f32,
    pub(crate) material_visible_surface_bin_penalty: f32,
    pub(crate) material_visible_surface_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_mean_penalty: f32,
    pub(crate) surface_normal_covered_bin_fraction: f32,
    pub(crate) surface_normal_bin_penalty: f32,
    pub(crate) surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) surface_normal_mean_penalty: f32,
    pub(crate) material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) material_visible_surface_normal_bin_penalty: f32,
    pub(crate) material_visible_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_normal_mean_penalty: f32,
    pub(crate) torus_angular_joint_coverage_fraction: f32,
    pub(crate) torus_angular_joint_coverage_penalty: f32,
    pub(crate) torus_angular_tube_coverage_fraction: f32,
    pub(crate) torus_angular_tube_coverage_penalty: f32,
    pub(crate) torus_angular_max_tube_gap_fraction: f32,
    pub(crate) torus_angular_tube_gap_penalty: f32,
    pub(crate) gaussian_scale_budget_loss: f32,
    pub(crate) gaussian_scale_budget_penalty: f32,
    pub(crate) gaussian_oversize_fraction: f32,
    pub(crate) gaussian_oversize_penalty: f32,
    pub(crate) render_density_psnr_db: f32,
    pub(crate) render_density_penalty: f32,
    pub(crate) render_color_psnr_db: f32,
    pub(crate) render_color_penalty: f32,
    pub(crate) render_depth_psnr_db: f32,
    pub(crate) render_depth_penalty: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dOpacityStats {
    pub(crate) finite: bool,
    pub(crate) min: f32,
    pub(crate) max: f32,
    pub(crate) mean: f32,
    pub(crate) active_min: f32,
    pub(crate) active_max: f32,
    pub(crate) active_mean: f32,
    pub(crate) active_count: usize,
    pub(crate) max_allowed: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dMaterialLivenessReport {
    pub(crate) material_visible_count: usize,
    pub(crate) inactive_material_visible_count: usize,
    pub(crate) inactive_material_visible_fraction: f32,
    pub(crate) inactive_material_logit_threshold: f32,
    pub(crate) max_inactive_material_opacity: f32,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy, Debug, Default, Serialize)]
pub(crate) struct Growth3dStrictSurfaceMaterializationReport {
    pub(crate) active_strict_count: usize,
    pub(crate) materialized_count: usize,
    pub(crate) materialized_fraction: f32,
    pub(crate) mean_material_opacity: f32,
    pub(crate) mean_visible_margin: f32,
    pub(crate) max_visible_margin: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dColorStateReport {
    pub(crate) available: bool,
    pub(crate) finite: bool,
    pub(crate) count: usize,
    pub(crate) active_count: usize,
    pub(crate) mean_abs: f32,
    pub(crate) max_abs: f32,
    pub(crate) active_mean_abs: f32,
    pub(crate) active_max_abs: f32,
    pub(crate) active_channel_stddev: [f32; 3],
    pub(crate) active_channel_stddev_mean: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dPermutationReport {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) max_position_error: f32,
    pub(crate) mean_position_error: f32,
    pub(crate) max_state_error: f32,
    pub(crate) mean_state_error: f32,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dSeedPerturbationReport {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) jitter_radius: f32,
    pub(crate) seed: u64,
    pub(crate) active_seed_count: usize,
    pub(crate) base_final_active_count: usize,
    pub(crate) perturbed_final_active_count: usize,
    pub(crate) active_count_ratio: f32,
    pub(crate) base_newly_activated_fraction: f32,
    pub(crate) perturbed_newly_activated_fraction: f32,
    pub(crate) base_final_active_max_radius: f32,
    pub(crate) perturbed_final_active_max_radius: f32,
    pub(crate) final_active_max_radius_ratio: f32,
    pub(crate) base_peak_mean_dx: f32,
    pub(crate) perturbed_peak_mean_dx: f32,
    pub(crate) peak_motion_ratio: f32,
    pub(crate) base_color_state_mean_abs: f32,
    pub(crate) perturbed_color_state_mean_abs: f32,
    pub(crate) color_state_mean_abs_ratio: f32,
    pub(crate) passed: bool,
}

#[derive(Serialize)]
pub(crate) struct Growth3dCatalogSanityReport {
    pub(crate) passed: bool,
    pub(crate) max_total_loss: f32,
    pub(crate) min_density_psnr_db: f32,
    pub(crate) min_color_psnr_db: f32,
    pub(crate) min_depth_psnr_db: f32,
    pub(crate) total_loss: f32,
    pub(crate) density_psnr_db: f32,
    pub(crate) color_psnr_db: f32,
    pub(crate) depth_psnr_db: f32,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct TorusAngularCoverageReport {
    pub(crate) ring_bins: usize,
    pub(crate) tube_bins: usize,
    pub(crate) threshold: f32,
    pub(crate) covered_joint_bins: usize,
    pub(crate) covered_ring_bins: usize,
    pub(crate) covered_tube_bins: usize,
    pub(crate) joint_coverage_fraction: f32,
    pub(crate) ring_coverage_fraction: f32,
    pub(crate) tube_coverage_fraction: f32,
    pub(crate) max_ring_gap_bins: usize,
    pub(crate) max_tube_gap_bins: usize,
    pub(crate) mean_distance: f32,
    pub(crate) max_distance: f32,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct SurfaceCoverageProfileReport {
    pub(crate) samples: usize,
    pub(crate) bins: usize,
    pub(crate) threshold: f32,
    pub(crate) covered_fraction: f32,
    pub(crate) covered_bin_fraction: f32,
    pub(crate) empty_bins: usize,
    pub(crate) min_bin_covered_fraction: f32,
    pub(crate) mean_bin_covered_fraction: f32,
    pub(crate) max_bin_covered_fraction: f32,
    pub(crate) assigned_particle_fraction: f32,
    pub(crate) covered_assigned_particle_fraction: f32,
    pub(crate) max_assigned_sample_fraction: f32,
    pub(crate) max_covered_assigned_sample_fraction: f32,
    pub(crate) bin_covered_fractions: Vec<f32>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct SurfaceNormalCoverageReport {
    pub(crate) samples: usize,
    pub(crate) normal_bins: usize,
    pub(crate) threshold: f32,
    pub(crate) target_bins: usize,
    pub(crate) covered_target_bins: usize,
    pub(crate) covered_target_bin_fraction: f32,
    pub(crate) covered_sample_fraction: f32,
    pub(crate) min_bin_covered_fraction: f32,
    pub(crate) mean_bin_covered_fraction: f32,
    pub(crate) max_bin_covered_fraction: f32,
    pub(crate) target_bin_sample_fractions: Vec<f32>,
    pub(crate) bin_covered_fractions: Vec<f32>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct Growth3dRobustnessReport {
    pub(crate) seed_count: usize,
    pub(crate) all_gate_passed: bool,
    pub(crate) all_catalog_sanity_passed: bool,
    pub(crate) all_strict_passed: bool,
    pub(crate) all_temporal_activation_progressive: bool,
    pub(crate) all_temporal_geometry_progressive: bool,
    pub(crate) all_local_front_coherent: bool,
    pub(crate) all_target_conditionless_lineage: bool,
    pub(crate) all_target_seed_conditionless_lineage: bool,
    pub(crate) all_target_growth_seed_mode: bool,
    pub(crate) all_no_seed_coordinate_scaffold: bool,
    pub(crate) all_active_extent_growth: bool,
    pub(crate) all_bounded_final_opacity: bool,
    pub(crate) all_material_visible_particles_live: bool,
    pub(crate) all_color_state_emerged: bool,
    pub(crate) all_permutation_consistent: bool,
    pub(crate) all_seed_perturbation_stable: bool,
    pub(crate) all_surface_coverage_profile: bool,
    pub(crate) all_material_visible_surface_coverage_profile: bool,
    pub(crate) all_surface_normal_coverage: bool,
    pub(crate) all_material_visible_surface_normal_coverage: bool,
    pub(crate) all_material_visible_surface_tail_bounded: bool,
    pub(crate) worst_strict_score: f32,
    pub(crate) max_render_loss: f32,
    pub(crate) min_density_psnr_db: f32,
    pub(crate) min_color_psnr_db: f32,
    pub(crate) min_depth_psnr_db: f32,
    pub(crate) min_active_seed_count: usize,
    pub(crate) max_active_seed_count: usize,
    pub(crate) min_final_active_count: usize,
    pub(crate) max_final_active_count: usize,
    pub(crate) min_newly_activated_fraction: f32,
    pub(crate) min_active_growth_ratio: f32,
    pub(crate) min_active_extent_bbox_ratio: f32,
    pub(crate) min_active_extent_min_axis_ratio: f32,
    pub(crate) max_final_opacity: f32,
    pub(crate) max_inactive_material_visible_fraction: f32,
    pub(crate) max_inactive_material_opacity: f32,
    pub(crate) min_final_active_color_state_mean_abs: f32,
    pub(crate) min_final_active_color_state_stddev_mean: f32,
    pub(crate) max_permutation_position_error: f32,
    pub(crate) max_permutation_state_error: f32,
    pub(crate) max_gaussian_scale_budget_loss: f32,
    pub(crate) max_gaussian_oversize_fraction: f32,
    pub(crate) min_perturbed_newly_activated_fraction: f32,
    pub(crate) min_perturbed_active_count_ratio: f32,
    pub(crate) max_perturbed_active_count_ratio: f32,
    pub(crate) min_perturbed_peak_motion_ratio: f32,
    pub(crate) max_perturbed_peak_motion_ratio: f32,
    pub(crate) max_front_nearest_previous_active_distance: f32,
    pub(crate) min_front_local_newly_activated_fraction: f32,
    pub(crate) max_final_material_visible_surface_tail_p99_distance: f32,
    pub(crate) max_final_material_visible_surface_tail_over_threshold_fraction: f32,
    pub(crate) max_final_material_visible_surface_tail_opacity_weighted_over_threshold_fraction:
        f32,
    pub(crate) min_final_active_target_coverage_fraction: f32,
    pub(crate) min_final_material_visible_target_coverage_fraction: f32,
    pub(crate) min_final_active_surface_covered_bin_fraction: f32,
    pub(crate) min_final_active_surface_mean_bin_covered_fraction: f32,
    pub(crate) min_final_material_visible_surface_covered_bin_fraction: f32,
    pub(crate) min_final_material_visible_surface_mean_bin_covered_fraction: f32,
    pub(crate) min_final_active_surface_normal_covered_bin_fraction: f32,
    pub(crate) min_final_active_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) min_final_material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) min_final_material_visible_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) min_torus_angular_joint_coverage_fraction: f32,
    pub(crate) min_torus_angular_tube_coverage_fraction: f32,
    pub(crate) max_torus_angular_tube_gap_fraction: f32,
    pub(crate) seeds: Vec<Growth3dRobustnessSeedReport>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct Growth3dRobustnessSeedReport {
    pub(crate) seed: u64,
    pub(crate) gate_passed: bool,
    pub(crate) strict_passed: bool,
    pub(crate) catalog_sanity_passed: bool,
    pub(crate) strict_score: f32,
    pub(crate) target_conditionless_lineage: bool,
    pub(crate) target_seed_conditionless_lineage: bool,
    pub(crate) target_growth_seed_mode: bool,
    pub(crate) no_seed_coordinate_scaffold: bool,
    pub(crate) render_loss: f32,
    pub(crate) density_psnr_db: f32,
    pub(crate) color_psnr_db: f32,
    pub(crate) depth_psnr_db: f32,
    pub(crate) active_seed_count: usize,
    pub(crate) final_active_count: usize,
    pub(crate) newly_activated_fraction: f32,
    pub(crate) active_extent_growth: bool,
    pub(crate) active_extent_bbox_ratio: f32,
    pub(crate) active_extent_min_axis_ratio: f32,
    pub(crate) final_opacity_max: f32,
    pub(crate) material_visible_particles_live: bool,
    pub(crate) inactive_material_visible_fraction: f32,
    pub(crate) max_inactive_material_opacity: f32,
    pub(crate) color_state_emerged: bool,
    pub(crate) final_active_color_state_mean_abs: f32,
    pub(crate) final_active_color_state_stddev_mean: f32,
    pub(crate) permutation_consistent: bool,
    pub(crate) permutation_max_position_error: f32,
    pub(crate) permutation_max_state_error: f32,
    pub(crate) gaussian_scale_budget: bool,
    pub(crate) gaussian_scale_budget_loss: f32,
    pub(crate) gaussian_oversize_fraction: f32,
    pub(crate) seed_perturbation_stable: bool,
    pub(crate) perturbed_newly_activated_fraction: f32,
    pub(crate) perturbed_active_count_ratio: f32,
    pub(crate) perturbed_peak_motion_ratio: f32,
    pub(crate) local_front_coherent: bool,
    pub(crate) front_local_newly_activated_fraction: f32,
    pub(crate) front_max_nearest_previous_active_distance: f32,
    pub(crate) temporal_activation_progressive: bool,
    pub(crate) temporal_geometry_progressive: bool,
    pub(crate) final_active_target_coverage_fraction: f32,
    pub(crate) final_material_visible_target_coverage_fraction: f32,
    pub(crate) surface_coverage_profile: bool,
    pub(crate) final_active_surface_covered_bin_fraction: f32,
    pub(crate) final_active_surface_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_coverage_profile: bool,
    pub(crate) final_material_visible_surface_covered_bin_fraction: f32,
    pub(crate) final_material_visible_surface_mean_bin_covered_fraction: f32,
    pub(crate) surface_normal_coverage: bool,
    pub(crate) final_active_surface_normal_covered_bin_fraction: f32,
    pub(crate) final_active_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_normal_coverage: bool,
    pub(crate) final_material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) final_material_visible_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) torus_angular_joint_coverage_fraction: f32,
    pub(crate) torus_angular_tube_coverage_fraction: f32,
    pub(crate) torus_angular_tube_gap_fraction: f32,
    pub(crate) final_active_surface_max: f32,
    pub(crate) material_visible_surface_tail_bounded: bool,
    pub(crate) final_material_visible_surface_tail_p99_distance: f32,
    pub(crate) final_material_visible_surface_tail_over_threshold_fraction: f32,
    pub(crate) final_material_visible_surface_tail_opacity_weighted_over_threshold_fraction: f32,
    pub(crate) failure_reasons: Vec<&'static str>,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dMotionReport {
    pub(crate) first_step_mean_dx: f32,
    pub(crate) peak_mean_dx: f32,
    pub(crate) peak_step: usize,
    pub(crate) final_step_mean_dx: f32,
    pub(crate) mean_dx: f32,
    pub(crate) late_mean_dx: f32,
    pub(crate) late_to_peak_ratio: f32,
    pub(crate) active_step_fraction: f32,
    pub(crate) sustained_step_fraction: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dFrontReport {
    pub(crate) transition_count: usize,
    pub(crate) newly_activated_count: usize,
    pub(crate) local_newly_activated_count: usize,
    pub(crate) local_newly_activated_fraction: f32,
    pub(crate) mean_nearest_previous_active_distance: f32,
    pub(crate) max_nearest_previous_active_distance: f32,
    pub(crate) max_allowed_distance: f32,
    pub(crate) finite: bool,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dDormantDriftReport {
    pub(crate) sampled_steps: usize,
    pub(crate) checked_rows: usize,
    pub(crate) drifting_rows: usize,
    pub(crate) drifting_fraction: f32,
    pub(crate) mean_dormant_displacement: f32,
    pub(crate) max_dormant_displacement: f32,
    pub(crate) max_allowed_displacement: f32,
    pub(crate) finite: bool,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dExtentReport {
    pub(crate) target_bounds_min: [f32; 3],
    pub(crate) target_bounds_max: [f32; 3],
    pub(crate) final_active_bounds_min: [f32; 3],
    pub(crate) final_active_bounds_max: [f32; 3],
    pub(crate) target_extent: [f32; 3],
    pub(crate) final_active_extent: [f32; 3],
    pub(crate) axis_extent_ratio: [f32; 3],
    pub(crate) min_axis_extent_ratio: f32,
    pub(crate) bbox_diagonal_ratio: f32,
    pub(crate) target_max_radius: f32,
    pub(crate) final_active_max_radius: f32,
    pub(crate) max_radius_ratio: f32,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct Growth3dTemporalReport {
    pub(crate) samples: Vec<Growth3dTemporalSampleReport>,
    pub(crate) first_growth_step: Option<usize>,
    pub(crate) half_activation_step: Option<usize>,
    pub(crate) full_activation_step: Option<usize>,
    pub(crate) activation_span_steps: usize,
    pub(crate) progressive_activation: bool,
    pub(crate) surface_mean_ratio: f32,
    pub(crate) target_coverage_mean_ratio: f32,
    pub(crate) target_coverage_fraction_delta: f32,
    pub(crate) geometry_progressive: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dTemporalSampleReport {
    pub(crate) steps: usize,
    pub(crate) active_count: usize,
    pub(crate) active_fraction: f32,
    pub(crate) newly_activated_count: usize,
    pub(crate) final_active_mean_radius: f32,
    pub(crate) final_active_max_radius: f32,
    pub(crate) mean_displacement: f32,
    pub(crate) active_surface: Growth3dSurfaceStats,
    pub(crate) target_coverage: TargetCoverageStats,
}

#[derive(Serialize)]
pub(crate) struct Growth3dActivationReport {
    pub(crate) active_seed_count: usize,
    pub(crate) inactive_seed_count: usize,
    pub(crate) final_active_count: usize,
    pub(crate) newly_activated_count: usize,
    pub(crate) newly_activated_fraction: f32,
    pub(crate) final_active_mean_radius: f32,
    pub(crate) final_active_max_radius: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dSurfaceStats {
    pub(crate) mean_distance: f32,
    pub(crate) max_distance: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dSurfaceTailReport {
    pub(crate) count: usize,
    pub(crate) threshold: f32,
    pub(crate) p95_distance: f32,
    pub(crate) p99_distance: f32,
    pub(crate) max_distance: f32,
    pub(crate) over_threshold_count: usize,
    pub(crate) over_threshold_fraction: f32,
    pub(crate) opacity_weighted_mean_distance: f32,
    pub(crate) opacity_weighted_over_threshold_fraction: f32,
}
