use super::*;

mod backend_history;
mod gradient_flow;
mod surface_material;
mod validation;

fn adaptive_line_search_candidate(
    scale: f32,
    min_final_active_count: usize,
    min_newly_activated_fraction: f32,
    max_temporal_activation_schedule_error: f32,
) -> DirectLineSearchCandidateReport {
    DirectLineSearchCandidateReport {
        inner_step: 0,
        scale,
        checkpoint_candidate: false,
        progress_candidate: false,
        selected_checkpoint: false,
        selected_progress: false,
        render_loss: 1.0,
        score: 1.0,
        density_psnr_db: 0.0,
        morphology_non_regressed: true,
        active_surface_max: 0.0,
        target_coverage_fraction: 0.0,
        material_visible_target_mean_distance: 0.0,
        material_visible_target_max_distance: 0.0,
        material_visible_target_coverage_fraction: 0.0,
        material_visible_inactive_fraction: 0.0,
        material_visible_max_inactive_opacity: 0.0,
        material_active_mean_opacity: 0.0,
        material_visible_count: 0,
        active_color_state_mean_abs: 0.0,
        active_color_state_max_abs: 0.0,
        active_color_state_stddev_mean: 0.0,
        surface_covered_bin_fraction: 0.0,
        surface_mean_bin_covered_fraction: 0.0,
        material_visible_surface_covered_bin_fraction: 0.0,
        material_visible_surface_mean_bin_covered_fraction: 0.0,
        surface_normal_covered_bin_fraction: 0.0,
        surface_normal_mean_bin_covered_fraction: 0.0,
        material_visible_surface_normal_covered_bin_fraction: 0.0,
        material_visible_surface_normal_mean_bin_covered_fraction: 0.0,
        material_visible_surface_tail_p99_distance: 0.0,
        material_visible_surface_tail_over_threshold_fraction: 0.0,
        min_active_extent_bbox_ratio: 0.0,
        min_active_extent_min_axis_ratio: 0.0,
        min_final_active_count,
        min_newly_activated_fraction,
        min_front_local_newly_activated_fraction: 1.0,
        max_front_liveness_margin: 0.0,
        min_front_liveness_candidate_count: 0,
        max_extent_front_liveness_margin: 0.0,
        min_extent_front_liveness_candidate_count: 0,
        max_temporal_front_liveness_margin: 0.0,
        min_temporal_front_liveness_candidate_count: 0,
        max_temporal_extent_front_liveness_margin: 0.0,
        min_temporal_extent_front_liveness_candidate_count: 0,
        max_temporal_activation_schedule_error,
        all_temporal_activation_progressive: false,
        all_temporal_geometry_progressive: false,
        train_final_loss: 1.0,
        train_grad_norm: 0.0,
        train_grad_scale: 1.0,
        failure_reasons: Vec::new(),
    }
}
