use super::prelude::*;

#[derive(Serialize)]
pub(crate) struct CliTrainingReport {
    pub(crate) preset: AutomataPreset,
    pub(crate) target_source: String,
    pub(crate) student_seed: u64,
    pub(crate) sgd: SgdConfig,
    pub(crate) report: TrainingRunReport,
    pub(crate) model_output: Option<String>,
    pub(crate) batch_source: TrainingBatchArg,
    pub(crate) rollout_supervision: Option<CliRolloutSupervisionReport>,
    pub(crate) mesh_rollout: Option<MeshRolloutReport>,
    pub(crate) render_loss: Option<MultiViewRenderLossReport>,
}

#[derive(Serialize)]
pub(crate) struct CliRenderLossEvalReport {
    pub(crate) target: MeshTargetArg,
    pub(crate) model: String,
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) render_loss: MultiViewRenderLossReport,
}

#[derive(Clone)]
pub(crate) struct Growth3dValidationConfig {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) extra_seeds: Vec<u64>,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) gate: Growth3dValidationGateArg,
    pub(crate) render: RenderLossConfig,
}

#[derive(Serialize)]
pub(crate) struct CliGrowth3dValidationReport {
    pub(crate) target: MeshTargetArg,
    pub(crate) model: String,
    pub(crate) source: Option<String>,
    pub(crate) position_features: bool,
    pub(crate) local_conditionless_lineage: bool,
    pub(crate) seed_coordinate_scaffold: bool,
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) non_opacity_seed_abs_max: f32,
    pub(crate) initial_color_state: Growth3dColorStateReport,
    pub(crate) final_color_state: Growth3dColorStateReport,
    pub(crate) permutation_consistency: Growth3dPermutationReport,
    pub(crate) seed_perturbation: Growth3dSeedPerturbationReport,
    pub(crate) mean_final_displacement: f32,
    pub(crate) final_opacity: Growth3dOpacityStats,
    pub(crate) final_material_opacity: Growth3dOpacityStats,
    pub(crate) final_material_liveness: Growth3dMaterialLivenessReport,
    pub(crate) activation: Growth3dActivationReport,
    pub(crate) initial_surface: Growth3dSurfaceStats,
    pub(crate) final_surface: Growth3dSurfaceStats,
    pub(crate) initial_active_surface: Growth3dSurfaceStats,
    pub(crate) final_active_surface: Growth3dSurfaceStats,
    pub(crate) initial_active_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) final_active_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) initial_material_visible_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) final_material_visible_surface_tail: Growth3dSurfaceTailReport,
    pub(crate) target_coverage_threshold: f32,
    pub(crate) initial_target_coverage: TargetCoverageStats,
    pub(crate) final_target_coverage: TargetCoverageStats,
    pub(crate) initial_active_target_coverage: TargetCoverageStats,
    pub(crate) final_active_target_coverage: TargetCoverageStats,
    pub(crate) initial_material_visible_target_coverage: TargetCoverageStats,
    pub(crate) final_material_visible_target_coverage: TargetCoverageStats,
    pub(crate) final_active_surface_coverage_profile: SurfaceCoverageProfileReport,
    pub(crate) final_material_visible_surface_coverage_profile: SurfaceCoverageProfileReport,
    pub(crate) final_active_surface_normal_coverage: SurfaceNormalCoverageReport,
    pub(crate) final_material_visible_surface_normal_coverage: SurfaceNormalCoverageReport,
    pub(crate) torus_angular_coverage: Option<TorusAngularCoverageReport>,
    pub(crate) extent: Growth3dExtentReport,
    pub(crate) motion: Growth3dMotionReport,
    pub(crate) temporal: Growth3dTemporalReport,
    pub(crate) front: Growth3dFrontReport,
    pub(crate) max_motion_per_step: f32,
    pub(crate) render_loss: MultiViewRenderLossReport,
    pub(crate) initial_gaussian_volume: GaussianVolumeStats,
    pub(crate) final_gaussian_volume: GaussianVolumeStats,
    pub(crate) strict_checks: Growth3dStrictChecksReport,
    pub(crate) strict_score: Growth3dStrictScoreReport,
    pub(crate) catalog_sanity: Growth3dCatalogSanityReport,
    pub(crate) robustness: Growth3dRobustnessReport,
    pub(crate) gate: Growth3dValidationGateArg,
    pub(crate) gate_passed: bool,
    pub(crate) strict_passed: bool,
}

#[derive(Serialize)]
pub(crate) struct Growth3dStrictChecksReport {
    pub(crate) passed: bool,
    pub(crate) no_position_features: bool,
    pub(crate) local_conditionless_lineage: bool,
    pub(crate) no_seed_coordinate_scaffold: bool,
    pub(crate) neutral_non_opacity_seed_state: bool,
    pub(crate) sparse_active_seed: bool,
    pub(crate) active_count_growth: bool,
    pub(crate) newly_activated_fraction: bool,
    pub(crate) active_front_expanded: bool,
    pub(crate) active_extent_growth: bool,
    pub(crate) nonzero_motion: bool,
    pub(crate) sustained_motion: bool,
    pub(crate) local_front_coherent: bool,
    pub(crate) temporal_activation_progressive: bool,
    pub(crate) temporal_geometry_progressive: bool,
    pub(crate) mean_displacement_growth: bool,
    pub(crate) bounded_final_opacity: bool,
    pub(crate) material_visible_particles_live: bool,
    pub(crate) color_state_emerged: bool,
    pub(crate) permutation_consistent: bool,
    pub(crate) surface_mean_improved: bool,
    pub(crate) surface_max_bounded: bool,
    pub(crate) surface_tail_bounded: bool,
    pub(crate) material_visible_surface_tail_bounded: bool,
    pub(crate) target_coverage_mean_improved: bool,
    pub(crate) target_coverage_max_bounded: bool,
    pub(crate) target_coverage_fraction: bool,
    pub(crate) material_visible_target_coverage_fraction: bool,
    pub(crate) surface_coverage_profile: bool,
    pub(crate) material_visible_surface_coverage_profile: bool,
    pub(crate) surface_normal_coverage: bool,
    pub(crate) material_visible_surface_normal_coverage: bool,
    pub(crate) torus_angular_coverage: bool,
    pub(crate) gaussian_scale_budget: bool,
    pub(crate) render_loss_passed: bool,
    pub(crate) failure_reasons: Vec<&'static str>,
}

#[derive(Serialize)]
pub(crate) struct Growth3dStrictScoreReport {
    pub(crate) score: f32,
    pub(crate) hard_failure_penalty: f32,
    pub(crate) temporal_activation_schedule_error: f32,
    pub(crate) temporal_activation_schedule_penalty: f32,
    pub(crate) material_visible_inactive_fraction: f32,
    pub(crate) material_visible_inactive_fraction_penalty: f32,
    pub(crate) material_visible_max_inactive_opacity: f32,
    pub(crate) material_visible_max_inactive_opacity_penalty: f32,
    pub(crate) surface_mean_ratio: f32,
    pub(crate) surface_mean_penalty: f32,
    pub(crate) surface_max_distance: f32,
    pub(crate) surface_max_penalty: f32,
    pub(crate) surface_tail_p99_distance: f32,
    pub(crate) surface_tail_p99_penalty: f32,
    pub(crate) surface_tail_over_threshold_fraction: f32,
    pub(crate) surface_tail_fraction_penalty: f32,
    pub(crate) material_visible_surface_tail_p99_distance: f32,
    pub(crate) material_visible_surface_tail_p99_penalty: f32,
    pub(crate) material_visible_surface_tail_over_threshold_fraction: f32,
    pub(crate) material_visible_surface_tail_fraction_penalty: f32,
    pub(crate) target_coverage_mean_ratio: f32,
    pub(crate) target_coverage_mean_penalty: f32,
    pub(crate) target_coverage_max_distance: f32,
    pub(crate) target_coverage_max_penalty: f32,
    pub(crate) target_coverage_fraction: f32,
    pub(crate) target_coverage_fraction_penalty: f32,
    pub(crate) material_visible_target_coverage_fraction: f32,
    pub(crate) material_visible_target_coverage_penalty: f32,
    pub(crate) active_extent_bbox_ratio: f32,
    pub(crate) active_extent_bbox_penalty: f32,
    pub(crate) active_extent_min_axis_ratio: f32,
    pub(crate) active_extent_min_axis_penalty: f32,
    pub(crate) surface_covered_bin_fraction: f32,
    pub(crate) surface_bin_penalty: f32,
    pub(crate) surface_mean_bin_covered_fraction: f32,
    pub(crate) surface_coverage_mean_penalty: f32,
    pub(crate) material_visible_surface_covered_bin_fraction: f32,
    pub(crate) material_visible_surface_bin_penalty: f32,
    pub(crate) material_visible_surface_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_mean_penalty: f32,
    pub(crate) surface_normal_covered_bin_fraction: f32,
    pub(crate) surface_normal_bin_penalty: f32,
    pub(crate) surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) surface_normal_mean_penalty: f32,
    pub(crate) material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) material_visible_surface_normal_bin_penalty: f32,
    pub(crate) material_visible_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_normal_mean_penalty: f32,
    pub(crate) gaussian_scale_budget_loss: f32,
    pub(crate) gaussian_scale_budget_penalty: f32,
    pub(crate) gaussian_oversize_fraction: f32,
    pub(crate) gaussian_oversize_penalty: f32,
    pub(crate) render_density_psnr_db: f32,
    pub(crate) render_density_penalty: f32,
    pub(crate) render_color_psnr_db: f32,
    pub(crate) render_color_penalty: f32,
    pub(crate) render_depth_psnr_db: f32,
    pub(crate) render_depth_penalty: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dOpacityStats {
    pub(crate) finite: bool,
    pub(crate) min: f32,
    pub(crate) max: f32,
    pub(crate) mean: f32,
    pub(crate) active_min: f32,
    pub(crate) active_max: f32,
    pub(crate) active_mean: f32,
    pub(crate) active_count: usize,
    pub(crate) max_allowed: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dMaterialLivenessReport {
    pub(crate) material_visible_count: usize,
    pub(crate) inactive_material_visible_count: usize,
    pub(crate) inactive_material_visible_fraction: f32,
    pub(crate) inactive_material_logit_threshold: f32,
    pub(crate) max_inactive_material_opacity: f32,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dColorStateReport {
    pub(crate) available: bool,
    pub(crate) finite: bool,
    pub(crate) count: usize,
    pub(crate) active_count: usize,
    pub(crate) mean_abs: f32,
    pub(crate) max_abs: f32,
    pub(crate) active_mean_abs: f32,
    pub(crate) active_max_abs: f32,
    pub(crate) active_channel_stddev: [f32; 3],
    pub(crate) active_channel_stddev_mean: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dPermutationReport {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) max_position_error: f32,
    pub(crate) mean_position_error: f32,
    pub(crate) max_state_error: f32,
    pub(crate) mean_state_error: f32,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dSeedPerturbationReport {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) jitter_radius: f32,
    pub(crate) seed: u64,
    pub(crate) active_seed_count: usize,
    pub(crate) base_final_active_count: usize,
    pub(crate) perturbed_final_active_count: usize,
    pub(crate) active_count_ratio: f32,
    pub(crate) base_newly_activated_fraction: f32,
    pub(crate) perturbed_newly_activated_fraction: f32,
    pub(crate) base_final_active_max_radius: f32,
    pub(crate) perturbed_final_active_max_radius: f32,
    pub(crate) final_active_max_radius_ratio: f32,
    pub(crate) base_peak_mean_dx: f32,
    pub(crate) perturbed_peak_mean_dx: f32,
    pub(crate) peak_motion_ratio: f32,
    pub(crate) base_color_state_mean_abs: f32,
    pub(crate) perturbed_color_state_mean_abs: f32,
    pub(crate) color_state_mean_abs_ratio: f32,
    pub(crate) passed: bool,
}

#[derive(Serialize)]
pub(crate) struct Growth3dCatalogSanityReport {
    pub(crate) passed: bool,
    pub(crate) max_total_loss: f32,
    pub(crate) min_density_psnr_db: f32,
    pub(crate) min_color_psnr_db: f32,
    pub(crate) min_depth_psnr_db: f32,
    pub(crate) total_loss: f32,
    pub(crate) density_psnr_db: f32,
    pub(crate) color_psnr_db: f32,
    pub(crate) depth_psnr_db: f32,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct TorusAngularCoverageReport {
    pub(crate) ring_bins: usize,
    pub(crate) tube_bins: usize,
    pub(crate) threshold: f32,
    pub(crate) covered_joint_bins: usize,
    pub(crate) covered_ring_bins: usize,
    pub(crate) covered_tube_bins: usize,
    pub(crate) joint_coverage_fraction: f32,
    pub(crate) ring_coverage_fraction: f32,
    pub(crate) tube_coverage_fraction: f32,
    pub(crate) max_ring_gap_bins: usize,
    pub(crate) max_tube_gap_bins: usize,
    pub(crate) mean_distance: f32,
    pub(crate) max_distance: f32,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct SurfaceCoverageProfileReport {
    pub(crate) samples: usize,
    pub(crate) bins: usize,
    pub(crate) threshold: f32,
    pub(crate) covered_fraction: f32,
    pub(crate) covered_bin_fraction: f32,
    pub(crate) empty_bins: usize,
    pub(crate) min_bin_covered_fraction: f32,
    pub(crate) mean_bin_covered_fraction: f32,
    pub(crate) max_bin_covered_fraction: f32,
    pub(crate) assigned_particle_fraction: f32,
    pub(crate) covered_assigned_particle_fraction: f32,
    pub(crate) max_assigned_sample_fraction: f32,
    pub(crate) max_covered_assigned_sample_fraction: f32,
    pub(crate) bin_covered_fractions: Vec<f32>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct SurfaceNormalCoverageReport {
    pub(crate) samples: usize,
    pub(crate) normal_bins: usize,
    pub(crate) threshold: f32,
    pub(crate) target_bins: usize,
    pub(crate) covered_target_bins: usize,
    pub(crate) covered_target_bin_fraction: f32,
    pub(crate) covered_sample_fraction: f32,
    pub(crate) min_bin_covered_fraction: f32,
    pub(crate) mean_bin_covered_fraction: f32,
    pub(crate) max_bin_covered_fraction: f32,
    pub(crate) target_bin_sample_fractions: Vec<f32>,
    pub(crate) bin_covered_fractions: Vec<f32>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct Growth3dRobustnessReport {
    pub(crate) seed_count: usize,
    pub(crate) all_gate_passed: bool,
    pub(crate) all_catalog_sanity_passed: bool,
    pub(crate) all_strict_passed: bool,
    pub(crate) all_temporal_activation_progressive: bool,
    pub(crate) all_temporal_geometry_progressive: bool,
    pub(crate) all_local_front_coherent: bool,
    pub(crate) all_no_seed_coordinate_scaffold: bool,
    pub(crate) all_active_extent_growth: bool,
    pub(crate) all_bounded_final_opacity: bool,
    pub(crate) all_material_visible_particles_live: bool,
    pub(crate) all_color_state_emerged: bool,
    pub(crate) all_permutation_consistent: bool,
    pub(crate) all_seed_perturbation_stable: bool,
    pub(crate) all_surface_coverage_profile: bool,
    pub(crate) all_material_visible_surface_coverage_profile: bool,
    pub(crate) all_surface_normal_coverage: bool,
    pub(crate) all_material_visible_surface_normal_coverage: bool,
    pub(crate) all_material_visible_surface_tail_bounded: bool,
    pub(crate) worst_strict_score: f32,
    pub(crate) max_render_loss: f32,
    pub(crate) min_density_psnr_db: f32,
    pub(crate) min_color_psnr_db: f32,
    pub(crate) min_depth_psnr_db: f32,
    pub(crate) min_active_seed_count: usize,
    pub(crate) max_active_seed_count: usize,
    pub(crate) min_final_active_count: usize,
    pub(crate) max_final_active_count: usize,
    pub(crate) min_newly_activated_fraction: f32,
    pub(crate) min_active_growth_ratio: f32,
    pub(crate) min_active_extent_bbox_ratio: f32,
    pub(crate) min_active_extent_min_axis_ratio: f32,
    pub(crate) max_final_opacity: f32,
    pub(crate) max_inactive_material_visible_fraction: f32,
    pub(crate) max_inactive_material_opacity: f32,
    pub(crate) min_final_active_color_state_mean_abs: f32,
    pub(crate) min_final_active_color_state_stddev_mean: f32,
    pub(crate) max_permutation_position_error: f32,
    pub(crate) max_permutation_state_error: f32,
    pub(crate) max_gaussian_scale_budget_loss: f32,
    pub(crate) max_gaussian_oversize_fraction: f32,
    pub(crate) min_perturbed_newly_activated_fraction: f32,
    pub(crate) min_perturbed_active_count_ratio: f32,
    pub(crate) max_perturbed_active_count_ratio: f32,
    pub(crate) min_perturbed_peak_motion_ratio: f32,
    pub(crate) max_perturbed_peak_motion_ratio: f32,
    pub(crate) max_front_nearest_previous_active_distance: f32,
    pub(crate) min_front_local_newly_activated_fraction: f32,
    pub(crate) max_final_material_visible_surface_tail_p99_distance: f32,
    pub(crate) max_final_material_visible_surface_tail_over_threshold_fraction: f32,
    pub(crate) max_final_material_visible_surface_tail_opacity_weighted_over_threshold_fraction:
        f32,
    pub(crate) min_final_active_target_coverage_fraction: f32,
    pub(crate) min_final_material_visible_target_coverage_fraction: f32,
    pub(crate) min_final_active_surface_covered_bin_fraction: f32,
    pub(crate) min_final_active_surface_mean_bin_covered_fraction: f32,
    pub(crate) min_final_material_visible_surface_covered_bin_fraction: f32,
    pub(crate) min_final_material_visible_surface_mean_bin_covered_fraction: f32,
    pub(crate) min_final_active_surface_normal_covered_bin_fraction: f32,
    pub(crate) min_final_active_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) min_final_material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) min_final_material_visible_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) seeds: Vec<Growth3dRobustnessSeedReport>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct Growth3dRobustnessSeedReport {
    pub(crate) seed: u64,
    pub(crate) gate_passed: bool,
    pub(crate) strict_passed: bool,
    pub(crate) catalog_sanity_passed: bool,
    pub(crate) strict_score: f32,
    pub(crate) no_seed_coordinate_scaffold: bool,
    pub(crate) render_loss: f32,
    pub(crate) density_psnr_db: f32,
    pub(crate) color_psnr_db: f32,
    pub(crate) depth_psnr_db: f32,
    pub(crate) active_seed_count: usize,
    pub(crate) final_active_count: usize,
    pub(crate) newly_activated_fraction: f32,
    pub(crate) active_extent_growth: bool,
    pub(crate) active_extent_bbox_ratio: f32,
    pub(crate) active_extent_min_axis_ratio: f32,
    pub(crate) final_opacity_max: f32,
    pub(crate) material_visible_particles_live: bool,
    pub(crate) inactive_material_visible_fraction: f32,
    pub(crate) max_inactive_material_opacity: f32,
    pub(crate) color_state_emerged: bool,
    pub(crate) final_active_color_state_mean_abs: f32,
    pub(crate) final_active_color_state_stddev_mean: f32,
    pub(crate) permutation_consistent: bool,
    pub(crate) permutation_max_position_error: f32,
    pub(crate) permutation_max_state_error: f32,
    pub(crate) gaussian_scale_budget: bool,
    pub(crate) gaussian_scale_budget_loss: f32,
    pub(crate) gaussian_oversize_fraction: f32,
    pub(crate) seed_perturbation_stable: bool,
    pub(crate) perturbed_newly_activated_fraction: f32,
    pub(crate) perturbed_active_count_ratio: f32,
    pub(crate) perturbed_peak_motion_ratio: f32,
    pub(crate) local_front_coherent: bool,
    pub(crate) front_local_newly_activated_fraction: f32,
    pub(crate) front_max_nearest_previous_active_distance: f32,
    pub(crate) temporal_activation_progressive: bool,
    pub(crate) temporal_geometry_progressive: bool,
    pub(crate) final_active_target_coverage_fraction: f32,
    pub(crate) final_material_visible_target_coverage_fraction: f32,
    pub(crate) surface_coverage_profile: bool,
    pub(crate) final_active_surface_covered_bin_fraction: f32,
    pub(crate) final_active_surface_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_coverage_profile: bool,
    pub(crate) final_material_visible_surface_covered_bin_fraction: f32,
    pub(crate) final_material_visible_surface_mean_bin_covered_fraction: f32,
    pub(crate) surface_normal_coverage: bool,
    pub(crate) final_active_surface_normal_covered_bin_fraction: f32,
    pub(crate) final_active_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) material_visible_surface_normal_coverage: bool,
    pub(crate) final_material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) final_material_visible_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) final_active_surface_max: f32,
    pub(crate) material_visible_surface_tail_bounded: bool,
    pub(crate) final_material_visible_surface_tail_p99_distance: f32,
    pub(crate) final_material_visible_surface_tail_over_threshold_fraction: f32,
    pub(crate) final_material_visible_surface_tail_opacity_weighted_over_threshold_fraction: f32,
    pub(crate) failure_reasons: Vec<&'static str>,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dMotionReport {
    pub(crate) first_step_mean_dx: f32,
    pub(crate) peak_mean_dx: f32,
    pub(crate) peak_step: usize,
    pub(crate) final_step_mean_dx: f32,
    pub(crate) mean_dx: f32,
    pub(crate) late_mean_dx: f32,
    pub(crate) late_to_peak_ratio: f32,
    pub(crate) active_step_fraction: f32,
    pub(crate) sustained_step_fraction: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dFrontReport {
    pub(crate) transition_count: usize,
    pub(crate) newly_activated_count: usize,
    pub(crate) local_newly_activated_count: usize,
    pub(crate) local_newly_activated_fraction: f32,
    pub(crate) mean_nearest_previous_active_distance: f32,
    pub(crate) max_nearest_previous_active_distance: f32,
    pub(crate) max_allowed_distance: f32,
    pub(crate) finite: bool,
    pub(crate) passed: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dExtentReport {
    pub(crate) target_bounds_min: [f32; 3],
    pub(crate) target_bounds_max: [f32; 3],
    pub(crate) final_active_bounds_min: [f32; 3],
    pub(crate) final_active_bounds_max: [f32; 3],
    pub(crate) target_extent: [f32; 3],
    pub(crate) final_active_extent: [f32; 3],
    pub(crate) axis_extent_ratio: [f32; 3],
    pub(crate) min_axis_extent_ratio: f32,
    pub(crate) bbox_diagonal_ratio: f32,
    pub(crate) target_max_radius: f32,
    pub(crate) final_active_max_radius: f32,
    pub(crate) max_radius_ratio: f32,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct Growth3dTemporalReport {
    pub(crate) samples: Vec<Growth3dTemporalSampleReport>,
    pub(crate) first_growth_step: Option<usize>,
    pub(crate) half_activation_step: Option<usize>,
    pub(crate) full_activation_step: Option<usize>,
    pub(crate) activation_span_steps: usize,
    pub(crate) progressive_activation: bool,
    pub(crate) surface_mean_ratio: f32,
    pub(crate) target_coverage_mean_ratio: f32,
    pub(crate) target_coverage_fraction_delta: f32,
    pub(crate) geometry_progressive: bool,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dTemporalSampleReport {
    pub(crate) steps: usize,
    pub(crate) active_count: usize,
    pub(crate) active_fraction: f32,
    pub(crate) newly_activated_count: usize,
    pub(crate) final_active_mean_radius: f32,
    pub(crate) final_active_max_radius: f32,
    pub(crate) mean_displacement: f32,
    pub(crate) active_surface: Growth3dSurfaceStats,
    pub(crate) target_coverage: TargetCoverageStats,
}

#[derive(Serialize)]
pub(crate) struct Growth3dActivationReport {
    pub(crate) active_seed_count: usize,
    pub(crate) inactive_seed_count: usize,
    pub(crate) final_active_count: usize,
    pub(crate) newly_activated_count: usize,
    pub(crate) newly_activated_fraction: f32,
    pub(crate) final_active_mean_radius: f32,
    pub(crate) final_active_max_radius: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dSurfaceStats {
    pub(crate) mean_distance: f32,
    pub(crate) max_distance: f32,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct Growth3dSurfaceTailReport {
    pub(crate) count: usize,
    pub(crate) threshold: f32,
    pub(crate) p95_distance: f32,
    pub(crate) p99_distance: f32,
    pub(crate) max_distance: f32,
    pub(crate) over_threshold_count: usize,
    pub(crate) over_threshold_fraction: f32,
    pub(crate) opacity_weighted_mean_distance: f32,
    pub(crate) opacity_weighted_over_threshold_fraction: f32,
}

#[derive(Serialize)]
pub(crate) struct CliRenderTrainingReport {
    pub(crate) target: MeshTargetArg,
    pub(crate) base_model: Option<String>,
    pub(crate) model_output: String,
    pub(crate) particle_count: usize,
    pub(crate) rollout_steps: usize,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) sgd: SgdConfig,
    pub(crate) report: RenderProxyTrainingReport,
    pub(crate) final_render_loss: MultiViewRenderLossReport,
    pub(crate) strict_gate_summary: CliRenderTrainingGateSummary,
    pub(crate) growth_validation: CliGrowth3dValidationReport,
    pub(crate) catalog_promotion_validations: Vec<CliGrowth3dValidationReport>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct CliRenderTrainingGateSummary {
    pub(crate) target: MeshTargetArg,
    pub(crate) source: Option<String>,
    pub(crate) strict_passed: bool,
    pub(crate) gate_passed: bool,
    pub(crate) catalog_sanity_passed: bool,
    pub(crate) strict_score: f32,
    pub(crate) hard_failure_penalty: f32,
    pub(crate) failure_reasons: Vec<&'static str>,
    pub(crate) no_position_features: bool,
    pub(crate) local_conditionless_lineage: bool,
    pub(crate) no_seed_coordinate_scaffold: bool,
    pub(crate) neutral_non_opacity_seed_state: bool,
    pub(crate) active_seed_count: usize,
    pub(crate) final_active_count: usize,
    pub(crate) active_count_delta: isize,
    pub(crate) newly_activated_fraction: f32,
    pub(crate) active_extent_growth: bool,
    pub(crate) active_extent_bbox_ratio: f32,
    pub(crate) active_extent_min_axis_ratio: f32,
    pub(crate) local_newly_activated_fraction: f32,
    pub(crate) mean_final_displacement: f32,
    pub(crate) peak_motion_per_step: f32,
    pub(crate) final_motion_per_step: f32,
    pub(crate) temporal_activation_progressive: bool,
    pub(crate) temporal_geometry_progressive: bool,
    pub(crate) target_coverage_mean_improvement: f32,
    pub(crate) target_coverage_fraction_delta: f32,
    pub(crate) target_coverage_fraction: f32,
    pub(crate) material_visible_target_coverage_fraction: f32,
    pub(crate) surface_covered_bin_fraction: f32,
    pub(crate) material_visible_surface_covered_bin_fraction: f32,
    pub(crate) surface_normal_covered_bin_fraction: f32,
    pub(crate) material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) render_loss_passed: bool,
    pub(crate) render_total_loss: f32,
    pub(crate) render_density_psnr_db: f32,
    pub(crate) render_color_psnr_db: f32,
    pub(crate) render_depth_psnr_db: f32,
}

impl CliRenderTrainingGateSummary {
    pub(crate) fn from_validation(report: &CliGrowth3dValidationReport) -> Self {
        Self {
            target: report.target,
            source: report.source.clone(),
            strict_passed: report.strict_passed,
            gate_passed: report.gate_passed,
            catalog_sanity_passed: report.catalog_sanity.passed,
            strict_score: report.strict_score.score,
            hard_failure_penalty: report.strict_score.hard_failure_penalty,
            failure_reasons: report.strict_checks.failure_reasons.clone(),
            no_position_features: report.strict_checks.no_position_features,
            local_conditionless_lineage: report.strict_checks.local_conditionless_lineage,
            no_seed_coordinate_scaffold: report.strict_checks.no_seed_coordinate_scaffold,
            neutral_non_opacity_seed_state: report.strict_checks.neutral_non_opacity_seed_state,
            active_seed_count: report.activation.active_seed_count,
            final_active_count: report.activation.final_active_count,
            active_count_delta: report.activation.final_active_count as isize
                - report.activation.active_seed_count as isize,
            newly_activated_fraction: report.activation.newly_activated_fraction,
            active_extent_growth: report.strict_checks.active_extent_growth,
            active_extent_bbox_ratio: report.extent.bbox_diagonal_ratio,
            active_extent_min_axis_ratio: report.extent.min_axis_extent_ratio,
            local_newly_activated_fraction: report.front.local_newly_activated_fraction,
            mean_final_displacement: report.mean_final_displacement,
            peak_motion_per_step: report.motion.peak_mean_dx,
            final_motion_per_step: report.motion.final_step_mean_dx,
            temporal_activation_progressive: report.temporal.progressive_activation,
            temporal_geometry_progressive: report.temporal.geometry_progressive,
            target_coverage_mean_improvement: report.initial_target_coverage.mean_distance
                - report.final_target_coverage.mean_distance,
            target_coverage_fraction_delta: report.final_target_coverage.covered_fraction
                - report.initial_target_coverage.covered_fraction,
            target_coverage_fraction: report.final_target_coverage.covered_fraction,
            material_visible_target_coverage_fraction: report
                .final_material_visible_target_coverage
                .covered_fraction,
            surface_covered_bin_fraction: report
                .final_active_surface_coverage_profile
                .covered_bin_fraction,
            material_visible_surface_covered_bin_fraction: report
                .final_material_visible_surface_coverage_profile
                .covered_bin_fraction,
            surface_normal_covered_bin_fraction: report
                .final_active_surface_normal_coverage
                .covered_target_bin_fraction,
            material_visible_surface_normal_covered_bin_fraction: report
                .final_material_visible_surface_normal_coverage
                .covered_target_bin_fraction,
            render_loss_passed: report.render_loss.passed,
            render_total_loss: report.render_loss.total_loss,
            render_density_psnr_db: report.render_loss.density_psnr_db,
            render_color_psnr_db: report.render_loss.color_psnr_db,
            render_depth_psnr_db: report.render_loss.depth_psnr_db,
        }
    }
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct RenderProxyTrainingReport {
    pub(crate) rounds: usize,
    pub(crate) supervised_steps_per_round: usize,
    pub(crate) objective: MeshRolloutObjectiveConfig,
    pub(crate) gradient_particles: usize,
    pub(crate) gradient_mode: RenderGradientModeArg,
    pub(crate) finite_diff_eps: f32,
    pub(crate) motion_gain: f32,
    pub(crate) perception_position_gain: f32,
    pub(crate) max_update_norm: f32,
    pub(crate) trajectory_supervision: bool,
    pub(crate) trajectory_render_gain: f32,
    pub(crate) trajectory_mesh_gain: f32,
    pub(crate) trajectory_render_samples: usize,
    pub(crate) liveness_gain: f32,
    pub(crate) liveness_front_radius: f32,
    pub(crate) liveness_update_multiplier: f32,
    pub(crate) coverage_gain: f32,
    pub(crate) coverage_samples: usize,
    pub(crate) coverage_mode: CoverageUpdateModeArg,
    pub(crate) coverage_softness: f32,
    pub(crate) coverage_repulsion_gain: f32,
    pub(crate) coverage_gap_gain: f32,
    pub(crate) coverage_repulsion_radius: f32,
    pub(crate) coverage_normal_weight: f32,
    pub(crate) extent_gain: f32,
    pub(crate) full_coverage_adjoint: bool,
    pub(crate) surface_gain: f32,
    pub(crate) surface_escape_gain: f32,
    pub(crate) opacity_gain: f32,
    pub(crate) material_liveness_gain: f32,
    pub(crate) material_tail_gain: f32,
    pub(crate) material_suppression_update_multiplier: f32,
    pub(crate) material_max_opacity_update: f32,
    pub(crate) scale_gain: f32,
    pub(crate) scale_budget_weight: f32,
    pub(crate) max_opacity_update: f32,
    pub(crate) direct_output_gradient_rms_cap: f32,
    pub(crate) direct_line_search: bool,
    pub(crate) direct_line_search_scales: Vec<f32>,
    pub(crate) direct_material_output_only: bool,
    pub(crate) training_backend: RenderTrainingBackendArg,
    pub(crate) direct_selection_seed_training: bool,
    pub(crate) selection_seed: Option<u64>,
    pub(crate) selection_seeds: Vec<u64>,
    pub(crate) initial_gaussian_volume: GaussianVolumeStats,
    pub(crate) final_gaussian_volume: GaussianVolumeStats,
    pub(crate) initial_render_loss: MultiViewRenderLossReport,
    pub(crate) final_render_loss: MultiViewRenderLossReport,
    pub(crate) selected_round: Option<usize>,
    pub(crate) history: Vec<RenderProxyTrainingHistoryEntry>,
}

#[derive(Clone, Debug, Serialize)]
pub(crate) struct RenderProxyTrainingHistoryEntry {
    pub(crate) round: usize,
    pub(crate) before_loss: f32,
    pub(crate) after_loss: f32,
    pub(crate) before_selection_loss: f32,
    pub(crate) before_selection_score: f32,
    pub(crate) before_selection_density_psnr_db: f32,
    pub(crate) before_selection_min_active_extent_bbox_ratio: f32,
    pub(crate) before_selection_min_active_extent_min_axis_ratio: f32,
    pub(crate) selection_loss: f32,
    pub(crate) selection_score: f32,
    pub(crate) before_density_psnr_db: f32,
    pub(crate) after_density_psnr_db: f32,
    pub(crate) selection_density_psnr_db: f32,
    pub(crate) selection_active_surface_max: f32,
    pub(crate) selection_target_coverage_fraction: f32,
    pub(crate) selection_material_visible_target_mean_distance: f32,
    pub(crate) selection_material_visible_target_max_distance: f32,
    pub(crate) selection_material_visible_target_coverage_fraction: f32,
    pub(crate) selection_material_visible_inactive_fraction: f32,
    pub(crate) selection_material_visible_max_inactive_opacity: f32,
    pub(crate) selection_material_active_mean_opacity: f32,
    pub(crate) selection_material_visible_count: usize,
    pub(crate) selection_surface_covered_bin_fraction: f32,
    pub(crate) selection_surface_mean_bin_covered_fraction: f32,
    pub(crate) selection_material_visible_surface_covered_bin_fraction: f32,
    pub(crate) selection_material_visible_surface_mean_bin_covered_fraction: f32,
    pub(crate) selection_surface_normal_covered_bin_fraction: f32,
    pub(crate) selection_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) selection_material_visible_surface_normal_covered_bin_fraction: f32,
    pub(crate) selection_material_visible_surface_normal_mean_bin_covered_fraction: f32,
    pub(crate) selection_material_visible_surface_tail_p99_distance: f32,
    pub(crate) selection_material_visible_surface_tail_over_threshold_fraction: f32,
    pub(crate) selection_min_active_extent_bbox_ratio: f32,
    pub(crate) selection_min_active_extent_min_axis_ratio: f32,
    pub(crate) selection_min_final_active_count: usize,
    pub(crate) selection_min_newly_activated_fraction: f32,
    pub(crate) selection_min_front_local_newly_activated_fraction: f32,
    pub(crate) selection_max_front_liveness_margin: f32,
    pub(crate) selection_min_front_liveness_candidate_count: usize,
    pub(crate) selection_max_extent_front_liveness_margin: f32,
    pub(crate) selection_min_extent_front_liveness_candidate_count: usize,
    pub(crate) selection_max_temporal_front_liveness_margin: f32,
    pub(crate) selection_min_temporal_front_liveness_candidate_count: usize,
    pub(crate) selection_max_temporal_extent_front_liveness_margin: f32,
    pub(crate) selection_min_temporal_extent_front_liveness_candidate_count: usize,
    pub(crate) selection_max_temporal_activation_schedule_error: f32,
    pub(crate) selection_all_temporal_activation_progressive: bool,
    pub(crate) selection_all_temporal_geometry_progressive: bool,
    pub(crate) selection_morphology_non_regressed: bool,
    pub(crate) selected_checkpoint: bool,
    pub(crate) rolled_back_to_best_checkpoint: bool,
    pub(crate) selection_worst_seed: u64,
    pub(crate) selection_worst_failure_reasons: Vec<&'static str>,
    pub(crate) before_color_psnr_db: f32,
    pub(crate) after_color_psnr_db: f32,
    pub(crate) before_depth_psnr_db: f32,
    pub(crate) after_depth_psnr_db: f32,
    pub(crate) train_initial_loss: f32,
    pub(crate) train_final_loss: f32,
    pub(crate) train_best_loss: f32,
    pub(crate) supervised_loss: f32,
    pub(crate) train_step_count: usize,
    pub(crate) train_loss_history: Vec<f32>,
    pub(crate) train_grad_norm: f32,
    pub(crate) train_grad_norm_history: Vec<f32>,
    pub(crate) train_grad_scale: f32,
    pub(crate) train_grad_scale_history: Vec<f32>,
    pub(crate) train_step_scale: f32,
    pub(crate) train_motion_output_delta_norm: f32,
    pub(crate) train_motion_memory_output_delta_norm: f32,
    pub(crate) train_liveness_output_delta_norm: f32,
    pub(crate) train_phase_output_delta_norm: f32,
    pub(crate) train_material_output_delta_norm: f32,
    pub(crate) direct_objective_diagnostics: DirectRolloutObjectiveDiagnostics,
    pub(crate) gradient_rms: f32,
    pub(crate) opacity_gradient_rms: f32,
    pub(crate) scale_gradient_rms: f32,
}

#[derive(Clone, Copy, Debug, Default, Serialize)]
pub(crate) struct DirectRolloutObjectiveDiagnostics {
    pub(crate) snapshots: usize,
    pub(crate) rows: usize,
    pub(crate) temporal_liveness_rms: f32,
    pub(crate) temporal_liveness_nonzero_fraction: f32,
    pub(crate) terminal_liveness_state_rms: f32,
    pub(crate) terminal_liveness_state_nonzero_fraction: f32,
    pub(crate) mesh_motion_liveness_rms: f32,
    pub(crate) mesh_motion_liveness_nonzero_fraction: f32,
    pub(crate) surface_escape_liveness_rms: f32,
    pub(crate) surface_escape_liveness_nonzero_fraction: f32,
    pub(crate) target_coverage_liveness_rms: f32,
    pub(crate) target_coverage_liveness_nonzero_fraction: f32,
    pub(crate) material_coverage_liveness_rms: f32,
    pub(crate) material_coverage_liveness_nonzero_fraction: f32,
    pub(crate) extent_front_liveness_rms: f32,
    pub(crate) extent_front_liveness_nonzero_fraction: f32,
    pub(crate) phase_rms: f32,
    pub(crate) phase_nonzero_fraction: f32,
    pub(crate) liveness_phase_memory_rms: f32,
    pub(crate) liveness_phase_memory_nonzero_fraction: f32,
    pub(crate) mesh_motion_rms: f32,
    pub(crate) mesh_motion_nonzero_fraction: f32,
    pub(crate) extent_front_motion_rms: f32,
    pub(crate) extent_front_motion_nonzero_fraction: f32,
    pub(crate) temporal_extent_motion_rms: f32,
    pub(crate) temporal_extent_motion_nonzero_fraction: f32,
    pub(crate) extent_motion_memory_rms: f32,
    pub(crate) extent_motion_memory_nonzero_fraction: f32,
    pub(crate) material_coverage_motion_rms: f32,
    pub(crate) material_coverage_motion_nonzero_fraction: f32,
    pub(crate) residual_velocity_rms: f32,
    pub(crate) residual_velocity_nonzero_fraction: f32,
    pub(crate) motion_memory_rms: f32,
    pub(crate) motion_memory_nonzero_fraction: f32,
    pub(crate) material_coverage_motion_memory_rms: f32,
    pub(crate) material_coverage_motion_memory_nonzero_fraction: f32,
    pub(crate) material_coverage_materialization_rms: f32,
    pub(crate) material_coverage_materialization_nonzero_fraction: f32,
    pub(crate) temporal_materialization_rms: f32,
    pub(crate) temporal_materialization_nonzero_fraction: f32,
    pub(crate) active_surface_materialization_rms: f32,
    pub(crate) active_surface_materialization_nonzero_fraction: f32,
    pub(crate) material_visibility_rms: f32,
    pub(crate) material_visibility_nonzero_fraction: f32,
    pub(crate) combined_pre_cap_rms: f32,
    pub(crate) combined_post_cap_rms: f32,
    pub(crate) mesh_motion_post_cap_rms: f32,
    pub(crate) mesh_motion_post_cap_nonzero_fraction: f32,
    pub(crate) residual_velocity_post_cap_rms: f32,
    pub(crate) residual_velocity_post_cap_nonzero_fraction: f32,
    pub(crate) motion_memory_post_cap_rms: f32,
    pub(crate) motion_memory_post_cap_nonzero_fraction: f32,
    pub(crate) liveness_post_cap_rms: f32,
    pub(crate) phase_post_cap_rms: f32,
    pub(crate) material_post_cap_rms: f32,
}

#[derive(Serialize)]
pub(crate) struct CliTorusTrainingReport {
    pub(crate) preset: AutomataPreset,
    pub(crate) target_source: String,
    pub(crate) student_seed: u64,
    pub(crate) sgd: SgdConfig,
    pub(crate) report: TrainingRunReport,
    pub(crate) model_output: Option<String>,
    pub(crate) robustness: TorusRobustnessReport,
    pub(crate) batch_source: TrainingBatchArg,
    pub(crate) training_mode: MeshTrainingModeArg,
    pub(crate) rollout_supervision: Option<CliRolloutSupervisionReport>,
}

#[derive(Clone, Copy, Debug, Serialize)]
pub(crate) struct CliRolloutSupervisionReport {
    pub(crate) particle_count: usize,
    pub(crate) rollout_steps: usize,
    pub(crate) rollouts: usize,
    pub(crate) temporal_samples: usize,
    pub(crate) update_prob: f32,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) motion_gain: Option<f32>,
    pub(crate) max_update_norm: Option<f32>,
    pub(crate) density_gain: Option<f32>,
    pub(crate) expansion_gain: Option<f32>,
    pub(crate) coverage_gain: Option<f32>,
    pub(crate) coverage_samples: Option<usize>,
    pub(crate) coverage_mode: Option<CoverageUpdateModeArg>,
    pub(crate) coverage_softness: Option<f32>,
    pub(crate) coverage_repulsion_gain: Option<f32>,
    pub(crate) coverage_gap_gain: Option<f32>,
    pub(crate) coverage_repulsion_radius: Option<f32>,
    pub(crate) coverage_normal_weight: Option<f32>,
    pub(crate) extent_gain: Option<f32>,
    pub(crate) color_gain: Option<f32>,
    pub(crate) aux_state_gain: Option<f32>,
    pub(crate) opacity_gain: Option<f32>,
    pub(crate) front_opacity_gain: Option<f32>,
    pub(crate) front_radius: Option<f32>,
    pub(crate) front_max_opacity_update: Option<f32>,
    pub(crate) front_motion_gate: Option<bool>,
    pub(crate) preserve_opacity_update: Option<bool>,
}

#[derive(Clone, Copy)]
pub(crate) struct MeshRolloutCaseConfig {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
}

#[derive(Serialize)]
pub(crate) struct MeshRolloutReport {
    pub(crate) passed: bool,
    pub(crate) max_initial_surface_distance: f32,
    pub(crate) mean_initial_surface_distance: f32,
    pub(crate) max_surface_distance: f32,
    pub(crate) mean_surface_distance: f32,
    pub(crate) mean_surface_improvement: f32,
    pub(crate) mean_surface_improvement_ratio: f32,
    pub(crate) max_target_coverage_distance: f32,
    pub(crate) mean_target_coverage_distance: f32,
    pub(crate) min_target_coverage_fraction: f32,
    pub(crate) max_color_target_error: f32,
    pub(crate) mean_color_target_error: f32,
    pub(crate) first_motion_per_step: f32,
    pub(crate) max_motion_per_step: f32,
    pub(crate) max_opacity_target_error: f32,
    pub(crate) min_final_opacity: f32,
    pub(crate) max_final_opacity: f32,
    pub(crate) cases: Vec<MeshRolloutCaseReport>,
}

#[derive(Serialize)]
pub(crate) struct MeshRolloutCaseReport {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) max_initial_surface_distance: f32,
    pub(crate) mean_initial_surface_distance: f32,
    pub(crate) max_surface_distance: f32,
    pub(crate) mean_surface_distance: f32,
    pub(crate) mean_surface_improvement: f32,
    pub(crate) mean_surface_improvement_ratio: f32,
    pub(crate) target_coverage_threshold: f32,
    pub(crate) max_target_coverage_distance: f32,
    pub(crate) mean_target_coverage_distance: f32,
    pub(crate) target_coverage_fraction: f32,
    pub(crate) max_color_target_error: f32,
    pub(crate) mean_color_target_error: f32,
    pub(crate) first_motion_per_step: f32,
    pub(crate) max_motion_per_step: f32,
    pub(crate) expected_final_opacity_logit: f32,
    pub(crate) min_final_opacity_logit: f32,
    pub(crate) max_final_opacity_logit: f32,
    pub(crate) max_opacity_target_error: f32,
    pub(crate) finite: bool,
}

#[derive(Clone, Copy)]
pub(crate) struct TorusRobustnessCaseConfig {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
}

#[derive(Serialize)]
pub(crate) struct TorusRobustnessReport {
    pub(crate) passed: bool,
    pub(crate) target_opacity_delta: f32,
    pub(crate) trained_opacity_delta: f32,
    pub(crate) target_motion_gain: f32,
    pub(crate) target_residual_decay: f32,
    pub(crate) max_target_position_error: f32,
    pub(crate) mean_target_position_error: f32,
    pub(crate) max_torus_surface_error: f32,
    pub(crate) max_color_target_error: f32,
    pub(crate) first_motion_per_step: f32,
    pub(crate) max_motion_per_step: f32,
    pub(crate) max_opacity_target_error: f32,
    pub(crate) min_final_opacity: f32,
    pub(crate) max_final_opacity: f32,
    pub(crate) cases: Vec<TorusRobustnessCaseReport>,
}

#[derive(Serialize)]
pub(crate) struct TorusRobustnessCaseReport {
    pub(crate) particle_count: usize,
    pub(crate) steps: usize,
    pub(crate) seed: u64,
    pub(crate) seed_scale: f32,
    pub(crate) seed_mode: ParticleSeed,
    pub(crate) torus_inner_radius: f32,
    pub(crate) torus_outer_radius: f32,
    pub(crate) max_initial_target_position_error: f32,
    pub(crate) mean_initial_target_position_error: f32,
    pub(crate) max_target_position_error: f32,
    pub(crate) mean_target_position_error: f32,
    pub(crate) max_torus_surface_error: f32,
    pub(crate) mean_torus_surface_error: f32,
    pub(crate) min_final_radial: f32,
    pub(crate) max_final_radial: f32,
    pub(crate) max_final_abs_z: f32,
    pub(crate) max_color_target_error: f32,
    pub(crate) mean_color_target_error: f32,
    pub(crate) first_motion_per_step: f32,
    pub(crate) max_motion_per_step: f32,
    pub(crate) expected_final_opacity_logit: f32,
    pub(crate) min_final_opacity_logit: f32,
    pub(crate) max_final_opacity_logit: f32,
    pub(crate) max_opacity_target_error: f32,
    pub(crate) finite: bool,
}
