use super::super::e2e::E2eHyperNpa2d;

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eRolloutHistoryEntry {
    pub(crate) step: usize,
    pub(crate) loss: f32,
    pub(crate) task_loss: f32,
    pub(crate) adapter_teacher_loss: f32,
    pub(crate) flow_matching_loss: f32,
    pub(crate) flow_self_rectification_loss: f32,
    pub(crate) amortization_distillation_loss: f32,
    pub(crate) amortization_residual_scale: f32,
    pub(crate) amortization_residual_rms: f32,
    pub(crate) amortization_grad_norm: f32,
    pub(crate) amortization_endpoint_psnr_db: Option<f32>,
    pub(crate) amortization_endpoint_p10_psnr_db: Option<f32>,
    pub(crate) learning_rate_scale: f32,
    pub(crate) base_learning_rate: f32,
    pub(crate) generator_learning_rate: f32,
    pub(crate) holdout_mean_psnr_db: Option<f32>,
    pub(crate) holdout_mean_loss: Option<f32>,
    pub(crate) base_grad_norm: f32,
    pub(crate) base_grad_scale: f32,
    pub(crate) generator_grad_norm: f32,
    pub(crate) generator_grad_scale: f32,
    pub(crate) examples_seen: usize,
    pub(crate) optimizer_examples_per_sec: f64,
    pub(crate) pool_seed_replacements: usize,
    pub(crate) particle_steps_per_sec: f64,
    pub(crate) dense_pair_interactions_per_sec: f64,
    pub(crate) elapsed_ms: f64,
    pub(crate) condition_adapter_ms: f64,
    pub(crate) rollout_loss_ms: f64,
    pub(crate) backward_update_ms: f64,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eAmortizationQualityReport {
    pub(crate) aggregate_composited_rgb_psnr_db: f32,
    pub(crate) p10_composited_rgb_psnr_db: f32,
    pub(crate) elapsed_ms: f64,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eRolloutQualityEntry {
    pub(crate) slug: String,
    pub(crate) total_loss: f32,
    pub(crate) splat_loss: f32,
    pub(crate) color_loss: f32,
    pub(crate) density_loss: f32,
    pub(crate) render_rgb_mse: f32,
    pub(crate) render_rgb_psnr_db: f32,
    pub(crate) composited_rgb_mse: f32,
    pub(crate) composited_rgb_psnr_db: f32,
    pub(crate) teacher_adapter_composited_rgb_psnr_db: Option<f32>,
    pub(crate) gap_to_teacher_adapter_db: Option<f32>,
    pub(crate) foreground_rgb_mse: f32,
    pub(crate) foreground_rgb_psnr_db: f32,
    pub(crate) density_mse: f32,
    pub(crate) density_psnr_db: f32,
    pub(crate) density_soft_iou: f32,
    pub(crate) passed: bool,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eRolloutHorizonSummary {
    pub(crate) rollout_steps: usize,
    pub(crate) seed_count: usize,
    pub(crate) seed_summaries: Vec<BurnE2eRolloutSeedSummary>,
    pub(crate) aggregate_composited_rgb_psnr_db: f32,
    pub(crate) p10_composited_rgb_psnr_db: f32,
    pub(crate) worst_seed_p10_composited_rgb_psnr_db: f32,
    pub(crate) min_composited_rgb_psnr_db: f32,
    pub(crate) teacher_adapter_aggregate_composited_rgb_psnr_db: Option<f32>,
    pub(crate) teacher_adapter_p10_composited_rgb_psnr_db: Option<f32>,
    pub(crate) p10_gap_to_teacher_adapter_db: Option<f32>,
    pub(crate) target_point_splat_p10_composited_rgb_psnr_db: f32,
    pub(crate) p10_gap_to_target_point_splat_db: f32,
    pub(crate) aggregate_density_psnr_db: f32,
    pub(crate) mean_density_soft_iou: f32,
    pub(crate) condition_shuffle_composited_psnr_gap_db: Option<f32>,
    pub(crate) generated_adapter_composited_psnr_gain_db: f32,
    pub(crate) mean_passed: bool,
    pub(crate) all_examples_passed: bool,
    pub(crate) conditional_control_passed: bool,
    pub(crate) passed: bool,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eRolloutSeedSummary {
    pub(crate) seed: u64,
    pub(crate) aggregate_composited_rgb_psnr_db: f32,
    pub(crate) p10_composited_rgb_psnr_db: f32,
    pub(crate) min_composited_rgb_psnr_db: f32,
    pub(crate) aggregate_density_psnr_db: f32,
    pub(crate) mean_density_soft_iou: f32,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eNearestTeacherEntry {
    pub(crate) holdout_slug: String,
    pub(crate) train_slug: String,
    pub(crate) condition_l2_distance: f32,
    pub(crate) render_rgb_psnr_db: f32,
    pub(crate) composited_rgb_psnr_db: f32,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eAdapterDiagnostics {
    pub(crate) parameterization: &'static str,
    pub(crate) parameter_count: usize,
    pub(crate) transport_parameter_count: usize,
    pub(crate) dense_controller_dims: Option<usize>,
    pub(crate) mean_l2_norm: f32,
    pub(crate) min_l2_norm: f32,
    pub(crate) max_l2_norm: f32,
    pub(crate) mean_pairwise_l2_distance: Option<f32>,
    pub(crate) min_pairwise_l2_distance: Option<f32>,
    pub(crate) mean_pairwise_cosine_similarity: Option<f32>,
    pub(crate) w1_dense_rms: Option<f32>,
    pub(crate) w2_dense_rms: Option<f32>,
    pub(crate) w1_down_rms: Option<f32>,
    pub(crate) w1_up_rms: Option<f32>,
    pub(crate) w2_down_rms: Option<f32>,
    pub(crate) w2_up_rms: Option<f32>,
    pub(crate) b1_rms: f32,
    pub(crate) b2_rms: f32,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eRolloutQualityReport {
    pub(crate) split: &'static str,
    pub(crate) examples: usize,
    pub(crate) particle_count: usize,
    pub(crate) rollout_steps: usize,
    pub(crate) update_prob: f32,
    pub(crate) seed: u64,
    pub(crate) representative_seed: u64,
    pub(crate) seed_count: usize,
    pub(crate) seed_summaries: Vec<BurnE2eRolloutSeedSummary>,
    pub(crate) psnr_threshold_db: f32,
    pub(crate) passed: bool,
    pub(crate) mean_passed: bool,
    pub(crate) all_examples_passed: bool,
    pub(crate) elapsed_ms: f64,
    pub(crate) particle_steps: f64,
    pub(crate) particle_steps_per_sec: f64,
    pub(crate) dense_pair_interactions_per_sec: f64,
    pub(crate) adapter_batches: usize,
    pub(crate) mean_total_loss: f32,
    pub(crate) mean_splat_loss: f32,
    pub(crate) mean_color_loss: f32,
    pub(crate) mean_density_loss: f32,
    pub(crate) mean_render_rgb_mse: f32,
    pub(crate) mean_render_rgb_psnr_db: f32,
    pub(crate) min_render_rgb_psnr_db: f32,
    pub(crate) max_render_rgb_psnr_db: f32,
    pub(crate) selection_metric: &'static str,
    pub(crate) selection_psnr_db: f32,
    pub(crate) selection_trajectory_count: usize,
    pub(crate) selection_horizon_min_steps: usize,
    pub(crate) horizon_summaries: Vec<BurnE2eRolloutHorizonSummary>,
    pub(crate) peak_horizon_p10_composited_rgb_psnr_db: f32,
    pub(crate) final_horizon_p10_composited_rgb_psnr_db: f32,
    pub(crate) peak_to_final_p10_drop_db: f32,
    pub(crate) target_point_splat_aggregate_composited_rgb_psnr_db: f32,
    pub(crate) target_point_splat_p10_composited_rgb_psnr_db: f32,
    pub(crate) p10_gap_to_target_point_splat_db: f32,
    pub(crate) aggregate_composited_rgb_mse: f32,
    pub(crate) aggregate_composited_rgb_psnr_db: f32,
    pub(crate) mean_composited_rgb_psnr_db: f32,
    pub(crate) median_composited_rgb_psnr_db: f32,
    pub(crate) p10_composited_rgb_psnr_db: f32,
    pub(crate) worst_seed_p10_composited_rgb_psnr_db: f32,
    pub(crate) min_composited_rgb_psnr_db: f32,
    pub(crate) max_composited_rgb_psnr_db: f32,
    pub(crate) teacher_adapter_aggregate_composited_rgb_psnr_db: Option<f32>,
    pub(crate) teacher_adapter_p10_composited_rgb_psnr_db: Option<f32>,
    pub(crate) p10_gap_to_teacher_adapter_db: Option<f32>,
    pub(crate) aggregate_foreground_rgb_mse: f32,
    pub(crate) aggregate_foreground_rgb_psnr_db: f32,
    pub(crate) aggregate_density_mse: f32,
    pub(crate) aggregate_density_psnr_db: f32,
    pub(crate) mean_density_soft_iou: f32,
    pub(crate) mean_condition_shuffle_render_rgb_psnr_db: Option<f32>,
    pub(crate) condition_shuffle_psnr_gap_db: Option<f32>,
    pub(crate) condition_shuffle_composited_rgb_psnr_db: Option<f32>,
    pub(crate) condition_shuffle_composited_psnr_gap_db: Option<f32>,
    pub(crate) base_only_composited_rgb_psnr_db: f32,
    pub(crate) generated_adapter_composited_psnr_gain_db: f32,
    pub(crate) base_only_density_psnr_db: f32,
    pub(crate) base_only_density_soft_iou: f32,
    pub(crate) dino_nearest_teacher_render_rgb_psnr_db: Option<f32>,
    pub(crate) dino_nearest_teacher_composited_rgb_psnr_db: Option<f32>,
    pub(crate) dino_nearest_teacher_entries: Vec<BurnE2eNearestTeacherEntry>,
    pub(crate) conditional_control_passed: bool,
    pub(crate) adapter_diagnostics: BurnE2eAdapterDiagnostics,
    pub(crate) entries: Vec<BurnE2eRolloutQualityEntry>,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eRolloutStabilityEntry {
    pub(crate) slug: String,
    pub(crate) reference_composited_rgb_psnr_db: f32,
    pub(crate) final_composited_rgb_psnr_db: f32,
    pub(crate) composited_rgb_psnr_drift_db: f32,
    pub(crate) reference_render_occupancy: f32,
    pub(crate) final_render_occupancy: f32,
    pub(crate) render_occupancy_drift: f32,
    pub(crate) final_position_overflow_fraction: f32,
    pub(crate) final_state_overflow_fraction: f32,
    pub(crate) reference_tail_mean_motion_per_step: f32,
    pub(crate) final_tail_mean_motion_per_step: f32,
    pub(crate) tail_motion_ratio: f32,
    pub(crate) finite: bool,
}

#[derive(Clone, serde::Serialize)]
pub(crate) struct BurnE2eRolloutStabilityReport {
    pub(crate) split: &'static str,
    pub(crate) evaluation_mode: &'static str,
    pub(crate) autodiff_graph_retained: bool,
    pub(crate) examples: usize,
    pub(crate) particle_count: usize,
    pub(crate) reference_steps: usize,
    pub(crate) rollout_steps: usize,
    pub(crate) tail_steps: usize,
    pub(crate) elapsed_ms: f64,
    pub(crate) particle_steps: f64,
    pub(crate) particle_steps_per_sec: f64,
    pub(crate) reference_aggregate_composited_rgb_psnr_db: f32,
    pub(crate) final_aggregate_composited_rgb_psnr_db: f32,
    pub(crate) aggregate_composited_rgb_psnr_drift_db: f32,
    pub(crate) reference_p10_composited_rgb_psnr_db: f32,
    pub(crate) final_p10_composited_rgb_psnr_db: f32,
    pub(crate) p10_composited_rgb_psnr_drift_db: f32,
    pub(crate) reference_mean_render_occupancy: f32,
    pub(crate) final_mean_render_occupancy: f32,
    pub(crate) mean_render_occupancy_drift: f32,
    pub(crate) mean_final_position_overflow_fraction: f32,
    pub(crate) max_final_position_overflow_fraction: f32,
    pub(crate) mean_final_state_overflow_fraction: f32,
    pub(crate) max_final_state_overflow_fraction: f32,
    pub(crate) mean_reference_tail_motion_per_step: f32,
    pub(crate) mean_final_tail_motion_per_step: f32,
    pub(crate) mean_tail_motion_ratio: f32,
    pub(crate) all_finite: bool,
    pub(crate) entries: Vec<BurnE2eRolloutStabilityEntry>,
}

pub(crate) struct BurnE2eRolloutOutput {
    pub(crate) backend: String,
    pub(crate) device: String,
    pub(crate) metrics: serde_json::Value,
    pub(crate) history: Vec<BurnE2eRolloutHistoryEntry>,
    pub(crate) final_loss: Option<f32>,
    pub(crate) generator: E2eHyperNpa2d,
    pub(crate) quality_validation: Option<BurnE2eRolloutQualityReport>,
    pub(crate) amortization_quality_validation: Option<BurnE2eAmortizationQualityReport>,
    pub(crate) stability_validation: Option<BurnE2eRolloutStabilityReport>,
}
